repository:	     sphericalwave/sphericalwave.github.io
# Permalinks
#permalink:           /:year/:month/:day/:title/
permalink: /:categories/:title 
# might want to copy 
# https://github.com/arturomoncadatorres/arturomoncadatorres.github.io/blob/main/_config.yml

# Setup
title:               Spherical Wave
url:                 https://sphericalwave.com
paginate:            3
paginate_path:    "/blog/page:num/"
baseurl:             ""
analytics_id:        

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Aaron Anthony
#  url:               https://twitter.com/mecid
  email:             aaron@sphericalwave.com

# Gems
plugins:
  - jekyll-avatar #don't think i need
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed     #generate atom feed, don't know what that is
  - jekyll-paginate

tag_page_layout: tag_page
tag_page_dir: tag