# Global Variables

title: SphericalWave
email: hello@sphericalwave.com
description: >- # this means to ignore newlines until "baseurl:"
  The Evolution of Consciousness
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: sphericalwave9
github:  sphericalwave
instagram: sphericalwave
#stackoverflow: aaronium112
youtube: sphericalwave

# Build settings
#theme: minima
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

#paginate: 5
#paginate_path: "/blog/page:num/"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
