repository:	     sphericalwave/sphericalwave.github.io
# Permalinks
permalink:           /:year/:month/:day/:title/

# Setup
title:               Spherical Wave
url:                 https://sphericalwave.com
paginate:            3
paginate_path:    "/blog/page:num/"
baseurl:             ""
analytics_id:        

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Aaron Anthony
#  url:               https://twitter.com/mecid
  email:             aaron@sphericalwave.com

# Gems
plugins:
  - jekyll-avatar
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

tag_page_layout: tag_page
tag_page_dir: tag