repository:	     sphericalwave/sphericalwave.github.io
# Permalinks
permalink:           /:year/:month/:day/:title/

# Setup
#theme: minima
title:               Spherical Wave
url:                 https://sphericalwave.com
paginate:            10
baseurl:             ""
analytics_id:        UA-18491817-18

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Aaron Anthony
#  url:               https://twitter.com/mecid
  email:             aaron@sphericalwave.com

# Gems
plugins:
  - jekyll-avatar
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
